name: getm-bfm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - netCDF4
  - h5py
  - rioxarray
  - rasterio
  - gdal
  - matplotlib
  - scipy
  - jupyterlab

## to create a conda env based on the yaml file:
# conda env create -f environment.yml
# conda activate getm-bfm

## to update the env after adding new packages:
# conda env update -f environment.yml --prune

