#!/bin/bash

restart_dir=/export/lv9/user/cgiannopoulos/home/pre-processing/hotstart
#restart_file=restart_199501_from200201.in
#restart_dir=/export/lv1/user/jvandermolen/model_output/active_runs/boundaries/dws_200m_nwes/
restart_file=restart_dws_500m_201412_hydro_10_layers_padded.nc
outdir=/export/lv9/user/cgiannopoulos/home/GETM_ERSEM_SETUPS/dws_500m/out/dws_500m/13x12/2014/12/



rm -f $outdir/restart.????.in

for i in `seq 0 9`;
do
  ln -s $restart_dir/$restart_file $outdir/restart.000$i.in
done
for i in `seq 10 99`;
do
  ln -s  $restart_dir/$restart_file $outdir/restart.00$i.in
done
for i in `seq 100 239`;
do
  ln -s $restart_dir/$restart_file  $outdir/restart.0$i.in
done
